# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a89ac9f946531c29426d9a34eaa5573f0958ab11fb66c127ded46e63cd0fbc4663e19633baa2ef8e004a2701a09765c127dd589be89fc0273f9b3e63dc13611

test:
  secret_key_base: aa29586c85c3c8a40731a10295132c202dfb74892fe85e9d0f2782de8ee7c7456d3eb8ca2a6c8c6619ceaece17abaacfc7d7e3338075073ca2764d38cb5dca8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
